const branding = {


  name:
    "Nyxora AI",



  header: {

    enabled:
      true,

    text:
      "Nyxora AI",

  },



  footer: {

    enabled:
      true,

    text:
      "Generated by Nyxora AI",

  },



  watermark: {

    enabled:
      true,

    text:
      "Nyxora AI",

    opacity:
      0.12,

  },



  slideNumber: {

    enabled:
      true,

  },


};


export default branding;