const presentationThemes = {

  nyxoraPremium: {

    name: "Nyxora Premium",

    description:
      "Dark premium AI presentation theme",

    colors: {

      background:
        "#050816",

      surface:
        "#111827",

      primary:
        "#6366F1",

      secondary:
        "#8B5CF6",

      accent:
        "#22D3EE",

      text:
        "#FFFFFF",

      mutedText:
        "#94A3B8",

      border:
        "#243047",

    },


    typography: {

      title:
        "Aptos Display",

      body:
        "Aptos",

    },


    branding: {

      header:
        "Nyxora AI",

      footer:
        "Generated by Nyxora AI",

    },


  },





  education: {

    name:
      "Education",

    description:
      "Clean classroom presentation theme",


    colors: {

      background:
        "#F8FAFC",

      surface:
        "#FFFFFF",

      primary:
        "#2563EB",

      secondary:
        "#7C3AED",

      accent:
        "#06B6D4",

      text:
        "#0F172A",

      mutedText:
        "#475569",

      border:
        "#CBD5E1",

    },


    typography: {

      title:
        "Aptos Display",

      body:
        "Aptos",

    },


    branding: {

      header:
        "Nyxora AI",

      footer:
        "Created with Nyxora AI",

    },


  },





  modernGradient: {

    name:
      "Modern Gradient",

    description:
      "Creative AI presentation theme",


    colors: {

      background:
        "#0F172A",

      surface:
        "#1E293B",

      primary:
        "#EC4899",

      secondary:
        "#8B5CF6",

      accent:
        "#14B8A6",

      text:
        "#FFFFFF",

      mutedText:
        "#CBD5E1",

      border:
        "#334155",

    },


    typography: {

      title:
        "Aptos Display",

      body:
        "Aptos",

    },


    branding: {

      header:
        "Nyxora AI",

      footer:
        "AI Generated Presentation",

    },


  },


};


export default presentationThemes;