import {
  ArrowUpRight,
  BookOpen,
  FileText,
  Sparkles,
  Users,
} from "lucide-react";


export default function WorkspaceOverview({
  classes,
  students,
  documents,
  onNavigate,
}) {

  const aiDocuments =
    documents.filter(
      (document) =>
        document.source === "ai"
    ).length;


  const stats = [
    {
      id: "classes",
      label: "Classes",
      value: classes.length,
      description: "Teaching groups",
      icon: BookOpen,

      iconStyle:
        "bg-fuchsia-500/10 text-fuchsia-300 border-fuchsia-400/15",

      glowStyle:
        "bg-fuchsia-500/10",
    },

    {
      id: "students",
      label: "Students",
      value: students.length,
      description: "Student profiles",
      icon: Users,

      iconStyle:
        "bg-violet-500/10 text-violet-300 border-violet-400/15",

      glowStyle:
        "bg-violet-500/10",
    },

    {
      id: "documents",
      label: "Documents",
      value: documents.length,
      description: "Learning resources",
      icon: FileText,

      iconStyle:
        "bg-cyan-500/10 text-cyan-300 border-cyan-400/15",

      glowStyle:
        "bg-cyan-500/10",
    },
  ];


  return (

    <div className="space-y-6">

      {/* =================================================
          HERO
      ================================================== */}

      <section
        className="
          relative
          overflow-hidden
          rounded-3xl
          border
          border-violet-400/20
          bg-gradient-to-br
          from-fuchsia-950/20
          via-[#0B1020]/95
          to-cyan-950/20
          p-7
          shadow-[0_20px_60px_rgba(0,0,0,0.18)]
          sm:p-8
        "
      >

        {/* AMBIENT GLOWS */}

        <div
          className="
            pointer-events-none
            absolute
            -left-20
            -top-20
            h-64
            w-64
            rounded-full
            bg-fuchsia-500/[0.10]
            blur-[100px]
          "
        />


        <div
          className="
            pointer-events-none
            absolute
            -bottom-24
            right-0
            h-72
            w-72
            rounded-full
            bg-cyan-500/[0.09]
            blur-[110px]
          "
        />


        <div
          className="
            pointer-events-none
            absolute
            left-[45%]
            top-[-120px]
            h-64
            w-64
            rounded-full
            bg-violet-500/[0.07]
            blur-[100px]
          "
        />


        {/* TOP ACCENT */}

        <div
          className="
            pointer-events-none
            absolute
            left-0
            top-0
            h-[2px]
            w-full
            bg-gradient-to-r
            from-fuchsia-500/70
            via-violet-500/70
            to-cyan-400/70
          "
        />


        <div className="relative z-10">

          {/* ICON */}

          <div
            className="
              flex
              h-14
              w-14
              items-center
              justify-center
              rounded-2xl
              border
              border-violet-300/20
              bg-gradient-to-br
              from-fuchsia-500/20
              via-violet-500/20
              to-cyan-400/20
              text-violet-200
              shadow-[0_0_30px_rgba(139,92,246,0.16)]
              backdrop-blur-xl
            "
          >

            <Sparkles
              size={24}
            />

          </div>


          {/* TITLE */}

          <h2
            className="
              mt-6
              max-w-3xl
              text-2xl
              font-bold
              tracking-tight
              text-white
              sm:text-3xl
            "
          >
            Your AI-powered teaching workspace
          </h2>


          {/* DESCRIPTION */}

          <p
            className="
              mt-3
              max-w-2xl
              text-sm
              leading-7
              text-slate-400
              sm:text-base
            "
          >
            Organize classes and students, manage educational
            resources and save content generated by Nyxora AI.
          </p>


          {/* AI DOCUMENT STATUS */}

          <div
            className="
              mt-7
              inline-flex
              items-center
              gap-2.5
              rounded-xl
              border
              border-violet-400/20
              bg-white/[0.035]
              px-4
              py-2.5
              text-sm
              text-violet-200
              shadow-lg
              shadow-violet-950/10
              backdrop-blur-xl
            "
          >

            <span
              className="
                flex
                h-7
                w-7
                items-center
                justify-center
                rounded-lg
                bg-gradient-to-br
                from-fuchsia-500/15
                via-violet-500/15
                to-cyan-500/15
              "
            >

              <Sparkles
                size={14}
                className="
                  text-violet-300
                "
              />

            </span>


            <span>
              <strong
                className="
                  font-semibold
                  text-white
                "
              >
                {aiDocuments}
              </strong>

              {" "}AI-generated documents saved
            </span>

          </div>

        </div>

      </section>


      {/* =================================================
          STATS
      ================================================== */}

      <section
        className="
          grid
          gap-4
          md:grid-cols-3
        "
      >

        {stats.map((stat) => {

          const Icon =
            stat.icon;


          return (

            <button
              key={
                stat.id
              }

              type="button"

              onClick={() =>
                onNavigate(
                  stat.id
                )
              }

              className="
                group
                relative
                overflow-hidden
                rounded-2xl
                border
                border-white/[0.08]
                bg-[#0B1020]/80
                p-5
                text-left
                shadow-[0_10px_35px_rgba(0,0,0,0.14)]
                backdrop-blur-xl
                transition-all
                duration-300

                hover:-translate-y-1
                hover:border-violet-400/25
                hover:bg-[#0E1426]
                hover:shadow-[0_18px_45px_rgba(0,0,0,0.22)]
              "
            >

              {/* CARD GLOW */}

              <div
                className={`
                  pointer-events-none
                  absolute
                  -right-12
                  -top-12
                  h-32
                  w-32
                  rounded-full
                  blur-[60px]
                  opacity-70
                  transition-opacity
                  duration-300
                  group-hover:opacity-100

                  ${stat.glowStyle}
                `}
              />


              <div
                className="
                  relative
                  z-10
                "
              >

                {/* TOP */}

                <div
                  className="
                    flex
                    items-start
                    justify-between
                    gap-4
                  "
                >

                  <div
                    className={`
                      flex
                      h-11
                      w-11
                      items-center
                      justify-center
                      rounded-xl
                      border

                      ${stat.iconStyle}
                    `}
                  >

                    <Icon
                      size={20}
                    />

                  </div>


                  <div
                    className="
                      flex
                      h-8
                      w-8
                      items-center
                      justify-center
                      rounded-lg
                      border
                      border-white/[0.06]
                      bg-white/[0.025]
                      text-slate-600
                      transition-all
                      duration-300

                      group-hover:border-violet-400/20
                      group-hover:text-violet-300
                    "
                  >

                    <ArrowUpRight
                      size={15}
                    />

                  </div>

                </div>


                {/* VALUE */}

                <p
                  className="
                    mt-6
                    text-3xl
                    font-bold
                    tracking-tight
                    text-white
                  "
                >
                  {stat.value}
                </p>


                {/* LABEL */}

                <p
                  className="
                    mt-2
                    font-semibold
                    text-slate-200
                  "
                >
                  {stat.label}
                </p>


                {/* DESCRIPTION */}

                <p
                  className="
                    mt-1
                    text-sm
                    text-slate-500
                  "
                >
                  {stat.description}
                </p>

              </div>

            </button>

          );

        })}

      </section>


      {/* =================================================
          AI INTEGRATION STATUS
      ================================================== */}

      <section
        className="
          relative
          overflow-hidden
          rounded-2xl
          border
          border-white/[0.08]
          bg-[#0B1020]/80
          p-6
          shadow-[0_10px_35px_rgba(0,0,0,0.14)]
          backdrop-blur-xl
        "
      >

        {/* SUBTLE GLOW */}

        <div
          className="
            pointer-events-none
            absolute
            -left-16
            top-1/2
            h-40
            w-40
            -translate-y-1/2
            rounded-full
            bg-violet-500/[0.08]
            blur-[70px]
          "
        />


        {/* LEFT IDENTITY LINE */}

        <div
          className="
            absolute
            bottom-5
            left-0
            top-5
            w-[2px]
            rounded-full
            bg-gradient-to-b
            from-fuchsia-400
            via-violet-400
            to-cyan-400
            shadow-[0_0_12px_rgba(139,92,246,0.55)]
          "
        />


        <div
          className="
            relative
            z-10
            flex
            items-start
            gap-4
          "
        >

          {/* ICON */}

          <div
            className="
              flex
              h-11
              w-11
              shrink-0
              items-center
              justify-center
              rounded-xl
              border
              border-violet-400/20
              bg-gradient-to-br
              from-fuchsia-500/10
              via-violet-500/15
              to-cyan-500/10
              text-violet-300
            "
          >

            <Sparkles
              size={20}
            />

          </div>


          {/* CONTENT */}

          <div>

            <div
              className="
                flex
                flex-wrap
                items-center
                gap-3
              "
            >

              <h3
                className="
                  font-semibold
                  text-white
                "
              >
                Nyxora AI integration
              </h3>


              <span
                className="
                  inline-flex
                  items-center
                  gap-1.5
                  rounded-full
                  border
                  border-emerald-400/15
                  bg-emerald-500/[0.07]
                  px-2.5
                  py-1
                  text-[11px]
                  font-medium
                  text-emerald-300
                "
              >

                <span
                  className="
                    h-1.5
                    w-1.5
                    rounded-full
                    bg-emerald-400
                    shadow-[0_0_7px_rgba(52,211,153,0.8)]
                  "
                />

                Connected

              </span>

            </div>


            <p
              className="
                mt-2
                max-w-3xl
                text-sm
                leading-6
                text-slate-500
              "
            >
              This Workspace is prepared to provide class,
              student and document context to Nyxora AI.
              Generated tests, homework, worksheets and reports
              will also be able to return here.
            </p>

          </div>

        </div>

      </section>

    </div>

  );

}