import {
  BookOpen,
  FileText,
  Sparkles,
  Users,
} from "lucide-react";


export default function WorkspaceOverview({
  classes,
  students,
  documents,
  onNavigate,
}) {

  const aiDocuments =
    documents.filter(
      (document) =>
        document.source === "ai"
    ).length;


  const stats = [
    {
      id: "classes",
      label: "Classes",
      value: classes.length,
      description: "Teaching groups",
      icon: BookOpen,
    },
    {
      id: "students",
      label: "Students",
      value: students.length,
      description: "Student profiles",
      icon: Users,
    },
    {
      id: "documents",
      label: "Documents",
      value: documents.length,
      description: "Learning resources",
      icon: FileText,
    },
  ];


  return (

    <div className="space-y-6">

      {/* HERO */}

      <section
        className="
          overflow-hidden
          rounded-3xl
          border
          border-violet-500/20
          bg-gradient-to-br
          from-violet-600/15
          via-[#0D1322]
          to-[#080C19]
          p-7
        "
      >

        <div
          className="
            flex
            h-12
            w-12
            items-center
            justify-center
            rounded-xl
            bg-violet-600
          "
        >
          <Sparkles size={22} />
        </div>


        <h2
          className="
            mt-5
            text-2xl
            font-semibold
            text-white
          "
        >
          Your AI-powered teaching workspace
        </h2>


        <p
          className="
            mt-2
            max-w-2xl
            leading-7
            text-gray-400
          "
        >
          Organize classes and students, manage educational
          resources and save content generated by Nyxora AI.
        </p>


        <div
          className="
            mt-6
            inline-flex
            items-center
            gap-2
            rounded-xl
            border
            border-violet-500/20
            bg-violet-500/10
            px-4
            py-2
            text-sm
            text-violet-300
          "
        >
          <Sparkles size={15} />

          {aiDocuments} AI-generated documents saved
        </div>

      </section>


      {/* STATS */}

      <section
        className="
          grid
          gap-4
          md:grid-cols-3
        "
      >

        {stats.map((stat) => {

          const Icon =
            stat.icon;


          return (

            <button
              key={stat.id}
              type="button"
              onClick={() =>
                onNavigate(stat.id)
              }
              className="
                rounded-2xl
                border
                border-[#242D43]
                bg-[#0D1322]
                p-5
                text-left
                transition
                hover:-translate-y-0.5
                hover:border-violet-500/40
                hover:bg-[#111827]
              "
            >

              <div
                className="
                  flex
                  h-10
                  w-10
                  items-center
                  justify-center
                  rounded-xl
                  bg-violet-500/10
                  text-violet-400
                "
              >
                <Icon size={19} />
              </div>


              <p
                className="
                  mt-5
                  text-3xl
                  font-semibold
                  text-white
                "
              >
                {stat.value}
              </p>


              <p
                className="
                  mt-2
                  font-medium
                  text-gray-200
                "
              >
                {stat.label}
              </p>


              <p
                className="
                  mt-1
                  text-sm
                  text-gray-500
                "
              >
                {stat.description}
              </p>

            </button>

          );

        })}

      </section>


      {/* AI STATUS */}

      <section
        className="
          rounded-2xl
          border
          border-[#242D43]
          bg-[#0D1322]
          p-6
        "
      >

        <div
          className="
            flex
            items-start
            gap-4
          "
        >

          <div
            className="
              flex
              h-10
              w-10
              shrink-0
              items-center
              justify-center
              rounded-xl
              bg-violet-500/10
              text-violet-400
            "
          >
            <Sparkles size={19} />
          </div>


          <div>

            <h3
              className="
                font-semibold
                text-white
              "
            >
              Nyxora AI integration
            </h3>


            <p
              className="
                mt-1
                max-w-2xl
                text-sm
                leading-6
                text-gray-500
              "
            >
              This Workspace is prepared to provide class,
              student and document context to Nyxora AI.
              Generated tests, homework, worksheets and reports
              will also be able to return here.
            </p>

          </div>

        </div>

      </section>

    </div>

  );

}